name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Haxe
        run: |
            sudo apt-get update
            sudo apt-get install -y haxe
            haxe --version

      - name: Setup haxelib library path
        run: |
            mkdir -p /home/runner/haxelib
            haxelib setup /home/runner/haxelib

      - name: Install OpenFL and dependencies
        run: |
            haxelib install openfl --quiet > /dev/null
            haxelib run openfl setup -y > /dev/null

      - name: Run OpenFL Test Project
        working-directory: tests
        run: openfl test cpp
